export const SHOW_SEARCH_RESULTS = 'SHOW_SEARCH_RESULTS';
export const SET_USER_SEARCHING = 'SET_USER_SEARCHING';
export const UPDATE_FILE_INPUT_LABEL = 'UPDATE_FILE_INPUT_LABEL';

export const PLACEHOLDER_TRY = 'TRY';